name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  api_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          submodules: false

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory "${{ github.workspace }}"

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'  # Ändra till den version du använder

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install Newman globally
        run: npm install -g newman

      - name: Install Node dependencies
        run: npm ci

      - name: Start the .NET API server in background
        run: |
          dotnet run --project server/server.csproj &
          sleep 10

      - name: Check absolute path (debugging)
        run: pwd

      - name: Run Newman API tests
        run: |
          newman run "server/api-test/API Övningar - Shop API.postman_collection.json" \
          -e "server/api-test/Shop API Environment.postman_environment.json"

      - name: Debug git config
        run: |
          git config --list --show-origin
          git status
          ls -la

  cypress_tests:
    needs: api_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          submodules: false

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory "${{ github.workspace }}"

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'  # Ändra till den version du använder

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: npm ci

      - name: Start the .NET API server in background
        run: |
          dotnet run --project server/server.csproj &
          sleep 10

      - name: Install Cypress dependencies
        run: cd cypress && npm ci

      - name: Run Cypress tests
        run: npm run cy-test
